### ISSUE TITLE
Some more "Hello World!" test cases 

### ISSUE THREAD

**Issue by rdebath** [tiro-finale/my-Brainfuck#1]
These tests all print the same hello world string as your test case, but, only the first works with your interpreter. Assuming you're going to fix it these test cases might help.

This one is a slightly improved version of yours (which works for you).
``` bf
++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>.
```
This one has lots of loops, in sequence. It works for the majority of interpreters.
```bf
++++++++[>+++++++++<-]>.<+++++++[>++++<-]>+.+++++++..+++.[-]<++++++++[>++++<-]>.<+++++++++++[>+++++<-]>.<++++++++[>+++<-]>.+++.------.--------.[-]<++++++++[>++++<-]>+.[-]++++++++++.<
```
This one has some crazy loop nesting.
```bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```
As you're using binary cells this should work too (but it'll take a long time for >8bit cells).
```bf
>>+[++[<+++>->+++<]>+++++++]<<<--.<.<--..<--.<<+++.<+.>>>.<.>>.>-.<<<<+.<<<<<<<<---.
```

**Comment by ms16183** [comment]
Thanks! Your examples are useful for me.
I Fixed my code and your examples are executed well (all samples showed "Hello World!").
